"""add_baja_usuario_y_revocacion_pedido

Revision ID: 5f885265fc53
Revises: 9a1523521f09
Create Date: 2026-09-14 08:41:34.420379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f885265fc53'
down_revision: Union[str, Sequence[str], None] = '9a1523521f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos', sa.Column('codigo_revocacion', sa.String(), nullable=True))
    op.add_column('pedidos', sa.Column('fecha_revocacion', sa.DateTime(timezone=True), nullable=True))
    op.add_column('usuarios', sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('usuarios', sa.Column('fecha_baja', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'fecha_baja')
    op.drop_column('usuarios', 'activo')
    op.drop_column('pedidos', 'fecha_revocacion')
    op.drop_column('pedidos', 'codigo_revocacion')
    # ### end Alembic commands ###
